site_name: Guo Note


theme:
  font:
    text: Roboto Mono
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode



plugins:
  - tags
  - search:
      lang: 
        - en
        - zh
      jieba_dict: dict.txt
  - blog:
      blog_dir: blog
      blog_toc: true
      archive_date_format: yyyy/MM
      post_readtime_words_per_minute: 300
      post_readtime: true
